### ISSUE TITLE
Failing on ZSH 5.7 on Mac

### ISSUE THREAD

**Issue by kriansa** [popstas/zsh-command-time#6]
Hello @popstas ,

Thanks for your work on this plugin. I tried to set it up but it's currently displaying a fixed message, as it were not evaluating the content between the backticks:

![screenshot 2019-02-01 18 04 32](https://user-images.githubusercontent.com/962032/52146851-2284a880-264c-11e9-8cf1-73a7ad17e48f.png)

**Comment by popstas** [comment]
@kriansa, thank you, you are right, problem was with this string, but in other quotes (variables in single quotes will not substitute).

Checked on docker container `zshusers/zsh-5.7.1`, please check in Macos
