### ISSUE TITLE
Is there a way to blacklist commands from being recorded, such as vim?

### ISSUE THREAD

**Issue by YangVincent** [popstas/zsh-command-time#7]

**Comment by popstas** [comment]
@YangVincent, @yutakatay, @syniuhin, @Sciencentistguy, I added variable `ZSH_COMMAND_TIME_EXCLUDE`, it is array with parts of excluded commands.

Example:
``` bash
ZSH_COMMAND_TIME_EXCLUDE=(vim mcedit)
```
